import Footer from "@/common/Footer";
import Navbar from "@/common/Navbar";
import FormStepper from "@/components/FormStepper";
import Head from "next/head";


export default function Index() {
  return (
    <>
      <Head>
        <title>African Bank | Online Loan Application Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex flex-col justify-between h-screen">
        {/* navbar section */}
        <Navbar />
        {/* main section */}
        <div className=" container p-8 mx-auto xl:px-0 flex flex-wrap mb-20 lg:gap-10 lg:flex-nowrap">
          <div className="w-full lg:w-1/2">
            <FormStepper />
          </div>
          <div className="w-full lg:w-1/2 p-3 relative h-48 ">
            <div className="absolute top-12 mr-5 h-full border-l border-[#00285A] opacity-[.7]"></div>
            <div className="flex-1 ml-5">
              <p className="max-w-2xl text-[29px] font-bold leading-snug tracking-tight text-[#fff] lg:leading-tight lg:text-4xl dark:text-white py-6">
                Need Help?
              </p>

              <p className="text-[12px] text-[#fff] dark:text-white py-6">
                Call Us:
                <span className="text-[14px] text-[#fff] font-bold">
                  {" "}
                  0861 123 456
                </span>
              </p>

              <p className="text-[12px] font-light leading-normal text-[#fff]  dark:text-white ">
                Monday to Friday from 8am to 5pm, Saturday from 9am to 1pm We
                are here for you during the National Lockdown. As an essential
                service, we are doing everything we can to maintain the level of
                customer service you expect from us. However, you may experience
                some delays. Please accept our sincere apologies.
              </p>
            </div>
          </div>
        </div>
        <Footer />
      </section>
    </>
  );
}
